version: 0.0

os: linux

files:
  - source: ./appspec.yml
    destination: /home/ubuntu
  - source: ./restartTomcat.sh
    destination: /home/ubuntu
  - source: ./aws/cloudwatch/awslogs.conf
    destination: /home/ubuntu
  - source: ./restartCloudWatch.sh
    destination: /home/ubuntu  
  - source: ./build/libs/ROOT.war
    destination: /var/lib/tomcat8/webapps
    
hooks:
  BeforwInstall:
   - location: ./restartTomcat.sh
     timeout: 180
     runas: ubuntu
  AfterInstall:
   - location: ./restartCloudWatch.sh
     timeout: 180
     runas: ubuntu
